- repo: itchyny/lightline.vim
- repo: junegunn/fzf.vim
- repo: mzlogin/vim-markdown-toc
- repo: tpope/vim-commentary
- repo: tpope/vim-fugitive
- repo: tpope/vim-repeat
- repo: tpope/vim-surround

# not in use
- { repo: lambdalisue/fern.vim, if: 0 }
- { repo: tyru/caw.vim, if: 0 }
